import type { DslKind, IntentRecord, ResourcePlan, SceneDocument, TwinComponent, TwinDocument } from "../core/types.js";
import { parseQueryDsl } from "../dsl/query.js";
import { parseDql } from "../dsl/dql.js";
import { parseTreeDsl } from "../dsl/tree.js";
import { parseMathDsl } from "../dsl/math.js";
import { validateScene } from "../dsl/scene.js";
import { validateTwin } from "../dsl/twin.js";
import { parseProjectDsl } from "../dsl/project.js";
import { parseObservationDsl } from "../dsl/observation.js";
import { parseImprovementDsl } from "../dsl/improvement.js";
import { validateT2cIntent } from "../dsl/intent.js";

export type GeneratedDslValue = ReturnType<typeof parseQueryDsl>|ReturnType<typeof parseDql>|ReturnType<typeof parseTreeDsl>|ReturnType<typeof parseMathDsl>|ReturnType<typeof parseProjectDsl>|ReturnType<typeof parseObservationDsl>|ReturnType<typeof parseImprovementDsl>|ResourcePlan|TwinDocument|SceneDocument|IntentRecord[];

const dslTextSchema:Record<string,unknown>={type:'object',properties:{dsl:{type:'string',minLength:8,maxLength:100000}},required:['dsl'],additionalProperties:false};
const sourceSpec={type:'object',properties:{kind:{type:'string',enum:['directory','archive','website','git','file']},location:{type:'string',minLength:1},role:{type:'string',enum:['manager','customer','project','internet','archive','derived','runtime','development']},include:{type:'array',items:{type:'string'},uniqueItems:true},exclude:{type:'array',items:{type:'string'},uniqueItems:true}},required:['kind','location','role','include','exclude'],additionalProperties:false};
const resourcePlanSchema:Record<string,unknown>={type:'object',properties:{document:{type:'object',properties:{schema:{const:'subactor.resource-plan/v1'},id:{type:'string',minLength:1},sources:{type:'array',items:sourceSpec,minItems:1},conversions:{type:'array',items:{type:'string'},minItems:1,uniqueItems:true},outputLogicalRoot:{type:'string',minLength:1},status:{const:'proposed'}},required:['schema','id','sources','conversions','outputLogicalRoot','status'],additionalProperties:false}},required:['document'],additionalProperties:false};
const componentSchema:Record<string,unknown>={type:'object',properties:{id:{type:'string'},type:{type:'string'},sourceUris:{type:'array',items:{type:'string'},uniqueItems:true},properties:{type:'object'},children:{type:'array'}},required:['id','type','sourceUris','properties','children'],additionalProperties:false};
const twinSchema:Record<string,unknown>={type:'object',properties:{document:{type:'object',properties:{schema:{const:'subactor.twin/v1'},id:{type:'string'},kind:{type:'string',enum:['actor','system','process','physical','conceptual']},observedAt:{type:'string'},sourceSnapshotHash:{type:'string',pattern:'^[a-f0-9]{64}$'},components:{type:'array',items:componentSchema}},required:['schema','id','kind','observedAt','sourceSnapshotHash','components'],additionalProperties:false}},required:['document'],additionalProperties:false};
const bindingSchema={type:'object',properties:{twinUri:{type:'string'},componentId:{type:'string'},scenePath:{type:'string'},primitive:{type:'string',enum:['cube','cylinder','sphere','scope']},position:{type:'array',items:{type:'number'},minItems:3,maxItems:3},size:{type:'array',items:{type:'number'},minItems:3,maxItems:3},propertyMap:{type:'object',additionalProperties:{type:'string'}},assetUri:{type:'string'}},required:['twinUri','scenePath','propertyMap'],additionalProperties:false};
const sceneSchema:Record<string,unknown>={type:'object',properties:{document:{type:'object',properties:{schema:{const:'subactor.scene/v1'},id:{type:'string'},format:{type:'string',enum:['openusd','gltf','3dtiles']},sourceTwinId:{type:'string'},bindings:{type:'array',items:bindingSchema,minItems:1}},required:['schema','id','format','bindings'],additionalProperties:false}},required:['document'],additionalProperties:false};
const intentRecordSchema:Record<string,unknown>={type:'object',properties:{schema:{const:'t2c.intent/v1'},id:{type:'string'},type:{type:'string',enum:['request','plan','decision','message','report','result','claim']},text:{type:'string',minLength:1},actor:{type:'string'},targetUris:{type:'array',items:{type:'string'}},ticket:{type:'string'},source:{type:'object'}},required:['schema','id','type','text','actor','targetUris'],additionalProperties:false};
const intentSchema:Record<string,unknown>={type:'object',properties:{document:{type:'array',items:intentRecordSchema,minItems:1}},required:['document'],additionalProperties:false};

function obj(x:unknown,name:string):Record<string,unknown>{if(!x||typeof x!=='object'||Array.isArray(x))throw new Error(`DSL_OBJECT_REQUIRED:${name}`);return x as Record<string,unknown>;}
function exact(x:Record<string,unknown>,keys:string[],name:string):void{for(const k of Object.keys(x))if(!keys.includes(k))throw new Error(`DSL_UNKNOWN_KEY:${name}:${k}`);for(const k of keys)if(!(k in x))throw new Error(`DSL_MISSING_KEY:${name}:${k}`);}
function strings(x:unknown,name:string):string[]{if(!Array.isArray(x)||!x.every(v=>typeof v==='string'))throw new Error(`DSL_STRING_ARRAY_REQUIRED:${name}`);return [...new Set(x)];}
function rawDsl(text:string):string{
  const trimmed=text.trim();
  const fenced=trimmed.match(/^```(?:[A-Za-z0-9_-]+)?\s*\n([\s\S]*?)\n```$/);
  return fenced?fenced[1].trim():trimmed;
}
function textDsl(x:unknown,parser:(s:string)=>GeneratedDslValue):GeneratedDslValue{const o=obj(x,'DSL');exact(o,['dsl'],'DSL');if(typeof o.dsl!=='string')throw new Error('DSL_TEXT_REQUIRED');return parser(rawDsl(o.dsl));}

function validateResourcePlan(x:unknown):ResourcePlan{const outer=obj(x,'RESOURCE_PLAN');exact(outer,['document'],'RESOURCE_PLAN');const d=obj(outer.document,'RESOURCE_PLAN_DOCUMENT');exact(d,['schema','id','sources','conversions','outputLogicalRoot','status'],'RESOURCE_PLAN_DOCUMENT');if(d.schema!=='subactor.resource-plan/v1'||d.status!=='proposed'||typeof d.id!=='string'||typeof d.outputLogicalRoot!=='string')throw new Error('RESOURCE_PLAN_INVALID');if(!Array.isArray(d.sources)||d.sources.length===0)throw new Error('RESOURCE_PLAN_SOURCES_REQUIRED');const sources=d.sources.map((raw,i)=>{const s=obj(raw,`RESOURCE_SOURCE_${i}`);exact(s,['kind','location','role','include','exclude'],`RESOURCE_SOURCE_${i}`);if(!['directory','archive','website','git','file'].includes(String(s.kind))||!['manager','customer','project','internet','archive','derived','runtime','development'].includes(String(s.role))||typeof s.location!=='string')throw new Error('RESOURCE_SOURCE_INVALID');return{kind:s.kind as ResourcePlan['sources'][number]['kind'],location:s.location,role:s.role as ResourcePlan['sources'][number]['role'],include:strings(s.include,'RESOURCE_INCLUDE'),exclude:strings(s.exclude,'RESOURCE_EXCLUDE')};});return{schema:'subactor.resource-plan/v1',id:d.id,sources,conversions:strings(d.conversions,'RESOURCE_CONVERSIONS'),outputLogicalRoot:d.outputLogicalRoot,status:'proposed'};}
function component(raw:unknown):TwinComponent{const c=obj(raw,'TWIN_COMPONENT');exact(c,['id','type','sourceUris','properties','children'],'TWIN_COMPONENT');if(typeof c.id!=='string'||typeof c.type!=='string')throw new Error('TWIN_COMPONENT_INVALID');return{id:c.id,type:c.type,sourceUris:strings(c.sourceUris,'TWIN_SOURCE_URIS'),properties:obj(c.properties,'TWIN_PROPERTIES'),children:Array.isArray(c.children)?c.children.map(component):(()=>{throw new Error('TWIN_CHILDREN_ARRAY_REQUIRED')})()};}
function validateTwinEnvelope(x:unknown):TwinDocument{const o=obj(x,'TWIN');exact(o,['document'],'TWIN');const d=obj(o.document,'TWIN_DOCUMENT');exact(d,['schema','id','kind','observedAt','sourceSnapshotHash','components'],'TWIN_DOCUMENT');const twin={schema:d.schema,id:d.id,kind:d.kind,observedAt:d.observedAt,sourceSnapshotHash:d.sourceSnapshotHash,components:Array.isArray(d.components)?d.components.map(component):[]} as TwinDocument;validateTwin(twin);return twin;}
function validateSceneEnvelope(x:unknown):SceneDocument{const o=obj(x,'SCENE');exact(o,['document'],'SCENE');const d=obj(o.document,'SCENE_DOCUMENT');const allowed=['schema','id','format','sourceTwinId','bindings'];for(const k of Object.keys(d))if(!allowed.includes(k))throw new Error(`SCENE_UNKNOWN_KEY:${k}`);if(d.schema!=='subactor.scene/v1'||typeof d.id!=='string'||!['openusd','gltf','3dtiles'].includes(String(d.format))||!Array.isArray(d.bindings))throw new Error('SCENE_INVALID');const scene={schema:'subactor.scene/v1',id:d.id,format:d.format,sourceTwinId:typeof d.sourceTwinId==='string'?d.sourceTwinId:undefined,bindings:d.bindings} as SceneDocument;validateScene(scene);return scene;}
function validateIntentEnvelope(x:unknown):IntentRecord[]{const o=obj(x,'INTENT');exact(o,['document'],'INTENT');return validateT2cIntent(o.document);}

export function generationContract(kind:DslKind):{schemaName:string;schema:Record<string,unknown>;validate:(x:unknown)=>GeneratedDslValue;instructions:string}{switch(kind){
  case'query':return{schemaName:'subactor_query_dsl',schema:dslTextSchema,validate:x=>textDsl(x,parseQueryDsl),instructions:'Return one queryDSL document. It must bind an exact URI Process, immutable source URIs, source snapshot hash, result kind and validations.'};
  case'dql':return{schemaName:'subactor_dql_crawl',schema:dslTextSchema,validate:x=>textDsl(x,parseDql),instructions:'Return one DQL crawl plan for sitemap and contextual website discovery. Stay within allowed hosts and explicit budgets.'};
  case'tree':return{schemaName:'subactor_tree_dsl',schema:dslTextSchema,validate:x=>textDsl(x,parseTreeDsl),instructions:'Return one treeDSL document using TREE and indented NODE lines.'};
  case'math':return{schemaName:'subactor_semantic_math_dsl',schema:dslTextSchema,validate:x=>textDsl(x,parseMathDsl),instructions:[
    'Return only semantic, non-authoritative mathDSL relations. The JSON `dsl` string MUST begin with `MATH <id>`.',
    'After the header use only `BIND Name = value [UNIT unit] [FROM [uri, ...]]` and `EXPR Name = AND(ref, ...)` / OR / NOT / EQ / GTE / LTE / GT / LT lines.',
    'Minimal valid example: MATH semantic-v1\\nBIND EvidencePresent = true FROM [urn:example:evidence]\\nEXPR SemanticallyReady = AND(EvidencePresent)',
    'Do not wrap DSL in Markdown fences and do not add prose.',
    'Never emit policy, permission, approval, mutation, publication, rate-limit or safety-gate fields; runtime projects those separately.',
  ].join(' ')};
  case'resource':return{schemaName:'subactor_resource_plan',schema:resourcePlanSchema,validate:validateResourcePlan,instructions:'Return a proposed resource plan. Never invent content hashes; the runtime materializes immutable resources after reading them.'};
  case'twin':return{schemaName:'subactor_twin',schema:twinSchema,validate:validateTwinEnvelope,instructions:'Return a Digital Twin projection grounded only in supplied resource URIs and source snapshot.'};
  case'scene':return{schemaName:'subactor_scene',schema:sceneSchema,validate:validateSceneEnvelope,instructions:'Return a scene projection bound to twin components. Prefer conceptual primitives when no verified CAD/BIM geometry exists.'};
  case'project':return{schemaName:'subactor_living_project_dsl',schema:dslTextSchema,validate:x=>textDsl(x,parseProjectDsl),instructions:'Return one projectDSL document defining sources, development workspace, observations, authority policy, iteration limits and scene format.'};
  case'observation':return{schemaName:'subactor_observation_dsl',schema:dslTextSchema,validate:x=>textDsl(x,parseObservationDsl),instructions:'Return one observationDSL document. Every runtime or environmental value must cite supplied source URIs and an observation time.'};
  case'improvement':return{schemaName:'subactor_improvement_dsl',schema:dslTextSchema,validate:x=>textDsl(x,parseImprovementDsl),instructions:'Return one propose-only improvementDSL document. Every action must cite existing evidence URIs. Never mark an action applied or approved.'};
  case'intent':return{schemaName:'subactor_intent',schema:intentSchema,validate:validateIntentEnvelope,instructions:'Patch the deterministic t2c.intent/v1 proposal only. Preserve source URIs and provenance; never publish, apply, or invent evidence.'};
}}
