import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import type { LivingIterationReceipt, LivingProjectDocument, LlmMode, MathDocument, ObservationDocument, ObservationRecord, ResourceDiff, ResourceRecord, SceneDocument, SourceRole, TreeDocument, TreeNode, TwinDocument } from "../core/types.js";
import { canonicalJson, contentUri, sha256 } from "../core/canonical.js";
import { scanSources } from "../ingestion/scanner.js";
import { parseProjectDsl, validateProject } from "../dsl/project.js";
import { renderObservationDsl, validateObservation } from "../dsl/observation.js";
import { evaluateMath, renderMathDsl } from "../dsl/math.js";
import { DqlCrawler, type FetchLike } from "../research/crawler.js";
import { parseDql } from "../dsl/dql.js";
import { Todo2CodeAdapter } from "../adapters/todo2code.js";
import { NlDslCompiler } from "../llm/nl-dsl-compiler.js";
import { renderOpenUsd, sceneDiff } from "../scene/openusd.js";
import { validateScene } from "../dsl/scene.js";
import { validateTwin } from "../dsl/twin.js";

async function readJson<T>(path:string):Promise<T>{return JSON.parse(await readFile(path,'utf8')) as T;}
async function readOptional<T>(path:string):Promise<T|undefined>{try{return await readJson<T>(path);}catch{return undefined;}}
async function writeJson(path:string,value:unknown):Promise<void>{await mkdir(dirname(path),{recursive:true});await writeFile(path,JSON.stringify(value,null,2)+'\n');}
function sourceSnapshot(resources:ResourceRecord[]):string{return sha256(canonicalJson(resources.map(r=>({uri:r.uri,path:r.sourcePath,role:r.sourceRole,sha256:r.sha256})).sort((a,b)=>a.path.localeCompare(b.path))));}
function resourceDiff(previous:ResourceRecord[],current:ResourceRecord[]):ResourceDiff{const a=new Map(previous.map(r=>[r.sourcePath,r.sha256])),b=new Map(current.map(r=>[r.sourcePath,r.sha256]));return{added:[...b].filter(([k])=>!a.has(k)).map(([k])=>k),changed:[...b].filter(([k,v])=>a.has(k)&&a.get(k)!==v).map(([k])=>k),removed:[...a].filter(([k])=>!b.has(k)).map(([k])=>k),unchanged:[...b].filter(([k,v])=>a.get(k)===v).map(([k])=>k)};}
function groupTree(project:LivingProjectDocument,resources:ResourceRecord[]):TreeDocument{const byRole=new Map<SourceRole,TreeNode>();for(const r of resources){const role=r.sourceRole??'project';if(!byRole.has(role))byRole.set(role,{id:`role-${role}`,uri:`subactor://project/${project.id}/role/${role}`,label:role,kind:'source-role',children:[]});byRole.get(role)!.children.push({id:r.id,uri:r.logicalUri,label:r.sourcePath.split('/').at(-1)??r.sourcePath,kind:'resource',parentId:`role-${role}`,relation:'contains',sourceUris:[r.uri],properties:{sha256:r.sha256,labels:r.labels??[]},children:[]});}return{schema:'subactor.tree/v1',id:`${project.id}-knowledge-tree`,roots:[{id:project.id,uri:`subactor://project/${project.id}`,label:project.name,kind:'living-project',children:[...byRole.values()]}]};}
function parseObservationValue(value:unknown):string|number|boolean{if(typeof value==='string'||typeof value==='number'||typeof value==='boolean')return value;return JSON.stringify(value);}
function observationsFromResources(project:LivingProjectDocument,resources:ResourceRecord[],texts:Map<string,string>,snapshot:string):ObservationDocument{
  const observations:ObservationRecord[]=[];let index=0;
  for(const resource of resources.filter(r=>r.sourceRole==='runtime')){const rawText=texts.get(resource.uri)??'';const fenced=rawText.match(/```(?:json)?\s*([\s\S]*?)```/i);const text=(fenced?.[1]??rawText).trim();let rows:unknown[]=[];try{const parsed=JSON.parse(text);rows=Array.isArray(parsed)?parsed:[parsed];}catch{rows=text.split(/\r?\n/).filter(Boolean).flatMap(line=>{try{return[JSON.parse(line)];}catch{return[];}});}
    for(const raw of rows){if(!raw||typeof raw!=='object'||Array.isArray(raw))continue;const row=raw as Record<string,unknown>,at=typeof row.observedAt==='string'?row.observedAt:typeof row.timestamp==='string'?row.timestamp:new Date(0).toISOString(),subject=typeof row.subjectUri==='string'?row.subjectUri:`subactor://project/${project.id}/runtime`,severity=['debug','info','warning','error','critical'].includes(String(row.severity))?String(row.severity) as ObservationRecord['severity']:'info';
      for(const [metric,value] of Object.entries(row)){if(['observedAt','timestamp','subjectUri','severity','labels','unit'].includes(metric))continue;observations.push({id:`obs-${++index}`,observedAt:at,subjectUri:subject,metric,value:parseObservationValue(value),unit:typeof row.unit==='string'?row.unit:undefined,severity,sourceUris:[resource.uri],labels:Array.isArray(row.labels)?row.labels.filter(x=>typeof x==='string') as string[]:[]});}
    }
  }
  return validateObservation({schema:'subactor.observation/v1',id:`${project.id}-observations`,sourceSnapshotHash:snapshot,observations});
}
function reasoning(project:LivingProjectDocument,resources:ResourceRecord[],developmentFingerprint:string,observations:ObservationDocument):MathDocument{
  const roles=new Set(resources.map(r=>r.sourceRole));const researchPresent=resources.some(r=>['manager','customer','project','archive','internet'].includes(String(r.sourceRole))),developmentPresent=developmentFingerprint!==sha256('[]'),runtimePresent=observations.observations.length>0;
  const managerUris=resources.filter(r=>r.sourceRole==='manager').map(r=>r.uri),developmentUris=resources.filter(r=>r.sourceRole==='development').map(r=>r.uri),runtimeUris=resources.filter(r=>r.sourceRole==='runtime').map(r=>r.uri);
  return{schema:'subactor.math/v1',id:`${project.id}-iteration-gates`,bindings:[
    {name:'ManagerApproved',value:project.policy.approved,sourceUris:managerUris},
    {name:'ResearchEvidencePresent',value:researchPresent,sourceUris:resources.filter(r=>['manager','customer','project','archive','internet'].includes(String(r.sourceRole))).map(r=>r.uri)},
    {name:'DevelopmentEvidencePresent',value:developmentPresent,sourceUris:developmentUris},
    {name:'RuntimeEvidencePresent',value:runtimePresent,sourceUris:runtimeUris},
    {name:'RequireResearch',value:project.policy.requireResearch,sourceUris:managerUris},
    {name:'RequireDevelopment',value:project.policy.requireDevelopmentEvidence,sourceUris:managerUris},
    {name:'RequireRuntime',value:project.policy.requireRuntimeEvidence,sourceUris:managerUris},
    {name:'AutoPublishScene',value:project.policy.autoPublishScene,sourceUris:managerUris},
    {name:'AllowRuntimeSelfModification',value:project.policy.allowRuntimeSelfModification,sourceUris:managerUris},
    {name:'SourceRoleCount',value:roles.size,unit:'count',sourceUris:resources.map(r=>r.uri)},
  ],expressions:{ResearchGate:{kind:'or',args:[{kind:'not',arg:{kind:'ref',name:'RequireResearch'}},{kind:'ref',name:'ResearchEvidencePresent'}]},DevelopmentGate:{kind:'or',args:[{kind:'not',arg:{kind:'ref',name:'RequireDevelopment'}},{kind:'ref',name:'DevelopmentEvidencePresent'}]},RuntimeGate:{kind:'or',args:[{kind:'not',arg:{kind:'ref',name:'RequireRuntime'}},{kind:'ref',name:'RuntimeEvidencePresent'}]},IterationAllowed:{kind:'and',args:[{kind:'ref',name:'ManagerApproved'},{kind:'ref',name:'ResearchGate'},{kind:'ref',name:'DevelopmentGate'},{kind:'ref',name:'RuntimeGate'}]},ScenePublishAllowed:{kind:'and',args:[{kind:'ref',name:'IterationAllowed'},{kind:'ref',name:'AutoPublishScene'}]},RuntimeSelfModificationAllowed:{kind:'and',args:[{kind:'ref',name:'IterationAllowed'},{kind:'ref',name:'AllowRuntimeSelfModification'}]}}};
}
function conceptualTwin(project:LivingProjectDocument,resources:ResourceRecord[],observations:ObservationDocument,snapshot:string,developmentFingerprint:string):TwinDocument{
  const roles=[...new Set(resources.map(r=>r.sourceRole??'project'))];return{schema:'subactor.twin/v1',id:`${project.id}-twin`,kind:project.profile==='biofoundry'?'physical':'conceptual',observedAt:new Date().toISOString(),sourceSnapshotHash:snapshot,components:[...roles.map((role,index)=>({id:`${role}-knowledge`,type:'knowledge-domain',sourceUris:resources.filter(r=>r.sourceRole===role).map(r=>r.uri),properties:{role,index,resourceCount:resources.filter(r=>r.sourceRole===role).length},children:[]})),{id:'development-model',type:'intent-evidence-graph',sourceUris:resources.filter(r=>r.sourceRole==='development').map(r=>r.uri),properties:{fingerprint:developmentFingerprint},children:[]},{id:'runtime-observations',type:'observation-stream',sourceUris:resources.filter(r=>r.sourceRole==='runtime').map(r=>r.uri),properties:{count:observations.observations.length,metrics:[...new Set(observations.observations.map(o=>o.metric))]},children:[]}]};
}
function conceptualScene(project:LivingProjectDocument,twin:TwinDocument):SceneDocument{return{schema:'subactor.scene/v1',id:`${project.id}-scene`,format:project.scene.format,sourceTwinId:twin.id,bindings:twin.components.map((c,index)=>({twinUri:`${contentUri('twin',twin)}#component=${encodeURIComponent(c.id)}`,componentId:c.id,scenePath:`/LivingProject/${c.id.replace(/[^A-Za-z0-9_]/g,'_')}`,primitive:'cube',position:[(index%4)*3,Math.floor(index/4)*3,0],size:[2,2,1],propertyMap:{resourceCount:'subactor:resourceCount',count:'subactor:observationCount',fingerprint:'subactor:developmentFingerprint'}}))};}
async function fixtureFetcher(base:string,mapPath:string):Promise<FetchLike>{const map=await readJson<Record<string,string>>(mapPath);return async input=>{const rel=map[String(input)];if(!rel)return new Response('not found',{status:404});return new Response(await readFile(resolve(base,rel),'utf8'),{status:200,headers:{'content-type':String(input).endsWith('.xml')?'application/xml':'text/html'}});};}
export class LivingProjectRuntime{
  constructor(readonly todo2code=new Todo2CodeAdapter(),readonly compiler=new NlDslCompiler()){}
  async load(configPath:string):Promise<LivingProjectDocument>{const text=await readFile(configPath,'utf8');return configPath.endsWith('.projectdsl')?parseProjectDsl(text):validateProject(JSON.parse(text));}
  async iterate(configPath:string,outDir:string,mode:LlmMode='deterministic'):Promise<LivingIterationReceipt>{
    const startedAt=new Date().toISOString(),absolute=resolve(configPath),base=dirname(absolute),project=await this.load(absolute);await mkdir(outDir,{recursive:true});
    const scanned=await scanSources(project.sources.map(s=>({path:resolve(base,s.path),role:s.role,logicalRoot:s.logicalRoot,labels:s.labels})));
    if(project.webResearch){const plan=parseDql(await readFile(resolve(base,project.webResearch.dqlFile),'utf8'));let crawler:DqlCrawler;if(project.webResearch.fixtureMapFile)crawler=new DqlCrawler(await fixtureFetcher(base,resolve(base,project.webResearch.fixtureMapFile)),async()=>{});else crawler=new DqlCrawler();const web=await crawler.crawl(plan);for(const page of web.pages){scanned.resources.push(page.resource);scanned.texts.set(page.resource.uri,page.markdown);}scanned.warnings.push(...web.warnings);}
    const resources=scanned.resources,researchHash=sourceSnapshot(resources),projectConfigHash=sha256(canonicalJson(project)),previousResources=await readOptional<ResourceRecord[]>(join(outDir,'state/resources.json'))??[],diff=resourceDiff(previousResources,resources),previous=await readOptional<LivingIterationReceipt>(join(outDir,'latest.json'));
    let development:unknown=[];const devRoot=resolve(base,project.development.root);if(project.development.fixture)development=await readJson(resolve(base,project.development.fixture));else if(await this.todo2code.available()){const devOut=join(outDir,'development');await this.todo2code.extract(devRoot,devOut);development=await this.todo2code.readLatestGraph(devRoot,devOut)??[];}
    const developmentFingerprint=sha256(canonicalJson(development)),observation=observationsFromResources(project,resources,scanned.texts,researchHash),observationHash=sha256(canonicalJson(observation));
    const stableKey=sha256(canonicalJson({researchHash,developmentFingerprint,observationHash,projectConfigHash}));if(previous&&previous.projectConfigHash===projectConfigHash&&previous.researchSnapshotHash===researchHash&&previous.developmentFingerprint===developmentFingerprint&&previous.observationSnapshotHash===observationHash)return{...previous,noChange:true,diff};
    const tree=groupTree(project,resources),detMath=reasoning(project,resources,developmentFingerprint,observation),detTwin=conceptualTwin(project,resources,observation,researchHash,developmentFingerprint),detScene=conceptualScene(project,detTwin),context={project,resources:resources.slice(0,200),development,observation,stableKey};
    const mathGen=await this.compiler.compile({kind:'math',text:`Evaluate the iteration gates for ${project.managerIntent}`,context,mode,deterministicValue:{dsl:renderMathDsl(detMath)}}),math=mathGen.value as MathDocument;
    const twinGen=await this.compiler.compile({kind:'twin',text:`Build the current Digital Twin projection for ${project.name}.`,context:{...context,math},mode,deterministicValue:{document:detTwin}}),twin=twinGen.value as TwinDocument;validateTwin(twin);
    const sceneGen=await this.compiler.compile({kind:'scene',text:`Build the current conceptual scene for ${project.name} without inventing geometry.`,context:{...context,math,twin},mode,deterministicValue:{document:detScene}}),scene=sceneGen.value as SceneDocument;validateScene(scene);
    const allowed=evaluateMath(math,'IterationAllowed')===true,publish=evaluateMath(math,'ScenePublishAllowed')===true,failures:string[]=[];if(!allowed)failures.push('IterationAllowed=false');if(!publish)failures.push('ScenePublishAllowed=false');
    const candidate=join(outDir,'candidate');await writeJson(join(candidate,'project.json'),project);await writeJson(join(candidate,'resources.json'),resources);await writeJson(join(candidate,'development.intent.json'),development);await writeJson(join(candidate,'tree.json'),tree);await writeJson(join(candidate,'math.json'),math);await writeFile(join(candidate,'math.dsl'),renderMathDsl(math));await writeJson(join(candidate,'observations.json'),observation);await writeFile(join(candidate,'observations.dsl'),renderObservationDsl(observation));await writeJson(join(candidate,'twin.json'),twin);await writeJson(join(candidate,'scene.json'),scene);await writeFile(join(candidate,'scene.usda'),renderOpenUsd(scene,twin));await writeJson(join(candidate,'scene.diff.json'),sceneDiff(await readOptional<SceneDocument>(join(outDir,'current/scene.json')),scene));await writeJson(join(candidate,'generation-audit.json'),{math:mathGen.audit,twin:twinGen.audit,scene:sceneGen.audit,warnings:scanned.warnings});
    if(publish){const current=join(outDir,'current');await mkdir(current,{recursive:true});for(const name of ['project.json','resources.json','development.intent.json','tree.json','math.json','math.dsl','observations.json','observations.dsl','twin.json','scene.json','scene.usda','scene.diff.json','generation-audit.json'])await writeFile(join(current,name),await readFile(join(candidate,name)));}
    const intentUri=contentUri('intent',development),treeUri=contentUri('tree',tree),mathUri=contentUri('math',math),observationUri=contentUri('observation',observation),twinUri=contentUri('twin',twin),sceneUri=contentUri('scene',scene),iterationId=randomUUID();const iterationCore={projectId:project.id,iterationId,researchHash,developmentFingerprint,observationHash,intentUri,treeUri,mathUri,observationUri,twinUri,sceneUri};const iterationUri=contentUri('iteration',iterationCore);
    const receipt:LivingIterationReceipt={schema:'subactor.living-iteration/v1',projectId:project.id,iterationId,noChange:false,startedAt,completedAt:new Date().toISOString(),projectConfigHash,researchSnapshotHash:researchHash,developmentFingerprint,observationSnapshotHash:observationHash,previousIterationUri:previous?.iterationUri??null,intentUri,treeUri,mathUri,observationUri,twinUri,sceneUri,iterationUri,diff,stages:[{name:'research',status:'succeeded',artifactUris:resources.map(r=>r.uri)},{name:'development',status:developmentFingerprint===sha256('[]')?'blocked':'succeeded',artifactUris:[intentUri],reason:developmentFingerprint===sha256('[]')?'todo2code evidence missing':undefined},{name:'runtime',status:observation.observations.length?'succeeded':'blocked',artifactUris:[observationUri],reason:observation.observations.length?'': 'runtime observations missing'},{name:'reasoning',status:allowed?'succeeded':'blocked',artifactUris:[mathUri],reason:allowed?undefined:'IterationAllowed=false'},{name:'twin',status:allowed?'succeeded':'blocked',artifactUris:[twinUri]},{name:'scene',status:publish?'succeeded':'blocked',artifactUris:[sceneUri],reason:publish?undefined:'ScenePublishAllowed=false'},{name:'feedback',status:'succeeded',artifactUris:[]}],validation:{ok:allowed&&publish,failures}};
    const feedback=[`# Living project feedback — ${project.name}`,`Manager intent: ${project.managerIntent}`,`Validation: ${receipt.validation.ok?'passed':'blocked'}`,`Research evidence: ${resources.length>0?'present':'missing'}`,`Development evidence: ${developmentFingerprint!==sha256('[]')?'present':'missing'}`,`Runtime observations: ${observation.observations.length>0?'present':'missing'}`,...failures.map(x=>`- ${x}`)].join('\n')+'\n';const feedbackPath=resolve(base,'feedback/latest.md');await mkdir(dirname(feedbackPath),{recursive:true});await writeFile(feedbackPath,feedback);const feedbackUri=contentUri('feedback',feedback);receipt.stages.at(-1)!.artifactUris=[feedbackUri];
    await writeJson(join(outDir,'state/resources.json'),resources);await writeJson(join(outDir,'state/key.json'),{stableKey});await writeJson(join(outDir,'receipts',`${iterationId}.json`),receipt);await writeJson(join(outDir,'latest.json'),receipt);await appendFile(join(outDir,'events.jsonl'),JSON.stringify({schema:'subactor.event/v1',eventType:'LivingIterationCompleted',projectId:project.id,iterationUri,occurredAt:receipt.completedAt,evidenceUris:[intentUri,treeUri,mathUri,observationUri,twinUri,sceneUri],validation:receipt.validation})+'\n');return receipt;
  }
}
