flowchart TD
%% generated in 0.02s
    js__archive_project_analyzer["js.archive-project-analyzer<br/>31 funcs"]
    js__f2md["js.f2md<br/>81 funcs"]
    js__live_twin_state["js.live-twin-state<br/>49 funcs"]
    py__f2md["py.f2md<br/>65 funcs"]
    scripts__cad_to_gltf["scripts.cad-to-gltf<br/>41 funcs"]
    scripts__scad_to_markdown["scripts.scad-to-markdown<br/>1 funcs"]
    src__dsl["src.dsl<br/>77 funcs"]
    src__runtime["src.runtime<br/>413 funcs"]
    src__serve["src.serve<br/>56 funcs"]
    py__f2md ==>|16| src__dsl
    scripts__cad_to_gltf ==>|11| js__archive_project_analyzer
    scripts__cad_to_gltf ==>|10| js__live_twin_state
    py__f2md ==>|7| src__serve
    py__f2md ==>|7| js__archive_project_analyzer
    scripts__cad_to_gltf ==>|6| src__runtime
    scripts__cad_to_gltf ==>|5| src__dsl
    py__f2md ==>|4| js__live_twin_state
    scripts__scad_to_markdown -->|2| js__archive_project_analyzer
    py__f2md -->|2| src__runtime
    py__f2md -->|1| js__f2md
