import type { SceneDocument, TwinDocument, SceneBinding } from "../core/types.js";
import { flattenTwin } from "../dsl/twin.js";
function ident(x:string):string{return x.replace(/[^A-Za-z0-9_]/g,'_').replace(/^([0-9])/,'_$1')||'Node';}
function q(x:string):string{return JSON.stringify(x);}
function vec(v:[number,number,number]|undefined,def:[number,number,number]):string{const x=v??def;return`(${x.map(n=>Number.isFinite(n)?n:0).join(', ')})`;}
function primitive(binding:SceneBinding):string{switch(binding.primitive){case'cylinder':return'Cylinder';case'sphere':return'Sphere';case'scope':return'Scope';default:return'Cube';}}
export function renderOpenUsd(scene:SceneDocument,twin:TwinDocument):string{
  const components=new Map(flattenTwin(twin).map(x=>[x.id,x]));const rootName=scene.id.toLowerCase().includes('biofoundry')?'Biofoundry':'LivingProject';const lines=['#usda 1.0','(',`    defaultPrim = "${rootName}"`,'    metersPerUnit = 1','    upAxis = "Z"',')','',`def Xform "${rootName}" {`];
  for(const binding of scene.bindings){const component=binding.componentId?components.get(binding.componentId):undefined;const name=ident(binding.scenePath.split('/').filter(Boolean).at(-1)??binding.componentId??'Node');const p=primitive(binding);lines.push(`    def Xform "${name}" {`,`        double3 xformOp:translate = ${vec(binding.position,[0,0,0])}`,'        uniform token[] xformOpOrder = ["xformOp:translate"]',`        custom string subactor:twinUri = ${q(binding.twinUri)}`,`        custom string subactor:componentId = ${q(binding.componentId??'')}`,`        custom string subactor:sourceUris = ${q((component?.sourceUris??[]).join(','))}`);
    if(component){for(const [key,value] of Object.entries(component.properties)){if(['position','size'].includes(key))continue;const attr=ident(key);if(typeof value==='number')lines.push(`        custom double subactor:${attr} = ${value}`);else if(typeof value==='boolean')lines.push(`        custom bool subactor:${attr} = ${value}`);else if(value!==null&&value!==undefined)lines.push(`        custom string subactor:${attr} = ${q(String(value))}`);}}
    if(p==='Scope')lines.push(`        def Scope "Metadata" {}`, '    }');else{lines.push(`        def ${p} "Geometry" {`);if(p==='Cube')lines.push('            double size = 1',`            double3 xformOp:scale = ${vec(binding.size?.map(x=>x/2) as [number,number,number]|undefined,[0.5,0.5,0.5])}`,'            uniform token[] xformOpOrder = ["xformOp:scale"]');else if(p==='Cylinder')lines.push(`            double radius = ${(binding.size?.[0]??1)/2}`,`            double height = ${binding.size?.[2]??1}`);else lines.push(`            double radius = ${(binding.size?.[0]??1)/2}`);lines.push('        }','    }');}
  }
  lines.push('}','');return lines.join('\n');
}
export function sceneDiff(before:SceneDocument|undefined,after:SceneDocument):{added:string[];changed:string[];removed:string[]}{const key=(b:SceneDocument['bindings'][number])=>b.componentId??b.scenePath;const a=new Map(after.bindings.map(x=>[key(x),JSON.stringify(x)])),b=new Map((before?.bindings??[]).map(x=>[key(x),JSON.stringify(x)]));return{added:[...a.keys()].filter(k=>!b.has(k)),changed:[...a.keys()].filter(k=>b.has(k)&&a.get(k)!==b.get(k)),removed:[...b.keys()].filter(k=>!a.has(k))};}
